version: "3"

services:
  api:
    # image: wildbookapi
    build: ./
    ports:
      - 5000:5000
    volumes:
      - ./src:/app/src
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: supersecret
